### PR TITLE
bump any version file

### PR DESCRIPTION
**Pull request by runningonfumes**
to be able to use this great utility in rails and other projects, I made the following changes
- use current working directory if no gemspec is found
- add option to provide custom versionfile location

I understand this might not fit your goal for this gem. In that case feel free to reject it :-)

### CODE REVIEW

**Comment by lanej** [comment]
:+1:

**Comment by dgeb** [comment]
@runningonfumes looks good - would you mind rebasing please?

**Comment by koenpunt** [comment]
:+1:

**Comment by dtaniwaki** [comment]
👍

**Comment by svenfuchs** [comment]
Thanks for the suggestion, @runningonfumes! And sorry for letting this get stale. I suppose the missing rebase made this get lost.

I have ported this to `2.0.0.pre.1` https://github.com/svenfuchs/gem-release/pull/64 in https://github.com/svenfuchs/gem-release/pull/64/commits/1362327fb4613d724a98020f6635e49ca36c3193

In order to give credit to your efforts I have also used `--author 'wimwintmolders <wim@up-nxt.com>'` on the commit.

Thanks again!

**Pull request closed without merging**
