### PR TITLE
Add gem release --github

### PR DESCRIPTION
**Pull request by svenfuchs**
Untested ...

refs https://github.com/svenfuchs/gem-release/issues/62

### CODE REVIEW

**Comment by kennyadsl** [comment]
Hey @svenfuchs ! Is there any plan to merge this feature. I want to use this gem for https://github.com/solidusio/solidus to make the release process easier and uniform. Part of our current releases workflow includes this step, and we'd be using `--github` option. 

Let me know if I can help to push this forward, thanks!

**Comment by PikachuEXE** [comment]
Rebase, fixed heredoc for Ruby 2.2 & all builds passed
Anyone tested this new feature?
@kennyadsl ?

**Comment by kennyadsl** [comment]
Not yet, but I'm still interested. Is there an easy way to run the gem from this branch locally?

**Comment by PikachuEXE** [comment]
Fixed several bugs like 
- missing error message
- unable to pass option in `release` command for github
- missing support for pretend mode
- Token not passed to request

I think there might be more bugs
Since I only tested with pretend mode :P

**Comment by PikachuEXE** [comment]
In your gem project's `Gemfile`:
```ruby
gem "gem-release", git: "https://github.com/svenfuchs/gem-release.git", branch: "sf-github-release"
```
Make sure you use `bundle exec gem release` (otherwise global installed version might be picked up)

**Comment by kennyadsl** [comment]
@PikachuEXE what I was trying to do is testing the gem locally without adding it to the bundle via the Gemfile. Do you think it's possible? Otherwise, I can definitely use `github:`+`branch:` or `path:` options. Thanks!

**Comment by PikachuEXE** [comment]
Even I when I test local `gem-release` code I need to add it via `path` option to `Gemfile`
I can't think of a way around it mate :)

Just open a new branch and commit Gemfile changes on it

**Comment by PikachuEXE** [comment]
@kennyadsl Got any progress on testing?

**Comment by kennyadsl** [comment]
@PikachuEXE I’m on vacation now and didn’t have the chance to test this yet, planning to give it a try when I come back in a couple of weeks. Will update here as well, thanks!

**Comment by kennyadsl** [comment]
@PikachuEXE I've just made the first test. I created this test repository https://github.com/kennyadsl/test_gem_release_gh (I can give you access if you want).

Tried to run the first release with `pretend` and `github` options:

```
bundle exec gem release --pretend -t -p  --github --t MY_TOKEN -d "Released via gem Release" -r "kennyadsl/test_gem_release_gh"
```
And I get this error:

```
Releasing test_gem_release_gh with version 0.1.0
Building test_gem_release_gh.gemspec
$ gem build test_gem_release_gh.gemspec

Pushing test_gem_release_gh-0.1.0.gem
$ gem push test_gem_release_gh-0.1.0.gem

Deleting left over gem file test_gem_release_gh-0.1.0.gem
$ rm -f test_gem_release_gh-0.1.0.gem

Tagging test_gem_release_gh as version 0.1.0
Creating git tag v0.1.0
$ git tag -am "tag v0.1.0" v0.1.0

Pushing tags to the origin git repository
$ git push --tags origin
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Release::Cmds::Release::GitHub
Did you mean?  Gem::Release::Cmds::Github
```

**Comment by PikachuEXE** [comment]
I think you are using old version of this branch
That was the first bug I found and fixed it soon after (with force push so I don't remember when did I fix it)
I guess you should make changes to `Gemfile` as mentioned in
https://github.com/svenfuchs/gem-release/pull/73#issuecomment-508617063
Maybe run `bundle update` too

**Comment by kennyadsl** [comment]
That's [what I did](https://github.com/kennyadsl/test_gem_release_gh/blob/4d928ca1233c4daad257c979843d7fe72a598126/Gemfile#L5) but it still keep [`29124d7ed83cce45871a1e148a821ef2aa7987c2`](https://github.com/kennyadsl/test_gem_release_gh/blob/master/Gemfile.lock#L3). 

If I try to add the last commit ref with , `ref: "55af839"` I get 
```
Revision 55af839 does not exist in the repository https://github.com/svenfuchs/gem-release.git. Maybe you misspelled it?
```

🤔

**Comment by kennyadsl** [comment]
Did it, I needed to use a longer ref!

**Comment by kennyadsl** [comment]
@PikachuEXE I'm having the same error using the last commit ref: https://github.com/kennyadsl/test_gem_release_gh/blob/aee096975b3ef9999487bc3e5c9d67c76eb4e078/Gemfile.lock#L3

**Comment by PikachuEXE** [comment]
If I understand it correctly
The new command cannot be run separately
https://github.com/svenfuchs/gem-release/tree/master/lib/rubygems/commands

You can run
`bundle exec gem release --github --pretend -t MY_TOKEN -d "Released via gem Release" -r "kennyadsl/test_gem_release_gh"`

**Comment by kennyadsl** [comment]
Got it! In my previous attempt (in January) I did setup [bundle local](https://bundler.io/v1.16/bundle_config.html#LOCAL-GIT-REPOS) to always use my local version of `gem-release`. This was making the Gemfile changes uneffective and I was still using the first version as you pointed out.

It's now working, I'll release a couple of test version for my test gem and will update here with results, thanks for your help!

**Comment by kennyadsl** [comment]
On a side note, I've noticed something unexpected: when I run:

```
bundle exec gem bump -p -s -t -r
```

it also creates [new releases on GitHub](https://github.com/kennyadsl/test_gem_release_gh/releases). Not sure how since I didn't run the `release --github` command and didn't specify the GH token anywhere (maybe those options are cached somewhere?). Or maybe it is now done by GitHub itself when a new tag is created (I can't find any resources about this in the GitHub documentation)?

<hr>

If I split the command:

```
bundle exec gem bump -p -s -t  # this works!
bundle exec gem release --github -t MY_TOKEN -d "Released via gem-release" -r "kennyadsl/test_gem_release_gh"
```

I get this error:

```
Creating GitHub release for test_gem_release_gh version v0.1.8
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Release::VERSION
Did you mean?  Gem::Release::Version
               Gem::Version
               Gem::VERSION
```

<hr>

Another thing: I think we should change the option `-t` for `--token` since in the `gem release` command it's already present for `--tag`. If `gem release --github` should always be run as a stand-alone command maybe it's better to create a new `gem github` command?

**Comment by kennyadsl** [comment]
I fixed a couple of issues with https://github.com/svenfuchs/gem-release/pull/84 but the release is still not created in GH and I'm trying to figure out why. Let me know if you have any idea. 🙂

**Comment by kennyadsl** [comment]
This is the error:

```
Status: 422
{"message":"Invalid request.\n\nFor 'properties/body', nil is not a string.","documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}
```

and it was due to a typo in declaring the argument names. I fixed it in the attached PR and I am now able to [create a release on GH](https://github.com/kennyadsl/test_gem_release_gh/releases/tag/v0.1.15)! 🎉

**Comment by PikachuEXE** [comment]
Let me work on it later this week (well Friday)
Maybe I can steal some time to work on this today too

**Comment by PikachuEXE** [comment]
Sorry, too many tasks this week
I hope I got time to work on this next week 😬

**Comment by kennyadsl** [comment]
Take your time, no hurry on my side. Thanks again for your help!

**Comment by PikachuEXE** [comment]
I removed the conflicting cmd line argument (short one) like `-t`
And print error message when rescuing abort error

Please take a look and see what else is incorrect / missing

**Comment by PikachuEXE** [comment]
@kennyadsl 
Yo
Just a regular reminder for testing this updated PR :3

**Comment by kennyadsl** [comment]
@PikachuEXE I tested this branch with

```
bundle exec gem bump -p -s -t && bundle exec gem release --github --token MY_TOKEN -d "Released via gem-release" --repo "kennyadsl/test_gem_release_gh"
```

And _almost_ everything worked well:

- [GitHub release](https://github.com/kennyadsl/test_gem_release_gh/releases/tag/v0.1.18)
- [RubyGems release](https://rubygems.org/gems/test_gem_release_gh/versions/0.1.18)

Here's the command output:

```
Bumping test_gem_release_gh from version 0.1.17 to 0.1.18
Changing version in lib/test_gem_release_gh/version.rb from 0.1.17 to 0.1.18

Staging lib/test_gem_release_gh/version.rb
$ git add lib/test_gem_release_gh/version.rb

Creating commit
$ git commit -m "Bump test_gem_release_gh to 0.1.18" -S
[master 650a5d9] Bump test_gem_release_gh to 0.1.18
 1 file changed, 1 insertion(+), 1 deletion(-)

Pushing to the origin git repository
$ git push origin
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 808 bytes | 269.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:kennyadsl/test_gem_release_gh.git
   68ab16c..650a5d9  master -> master

Tagging test_gem_release_gh as version 0.1.18
Creating git tag v0.1.18
$ git tag -am "tag v0.1.18" v0.1.18 --sign

Pushing tags to the origin git repository
$ git push --tags origin
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 537 bytes | 537.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:kennyadsl/test_gem_release_gh.git
 * [new tag]         v0.1.18 -> v0.1.18

All is good, thanks my friend.


Releasing test_gem_release_gh with version 0.1.18
Building test_gem_release_gh.gemspec
$ gem build test_gem_release_gh.gemspec
WARNING:  description and summary are identical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: test_gem_release_gh
  Version: 0.1.18
  File: test_gem_release_gh-0.1.18.gem

Pushing test_gem_release_gh-0.1.18.gem
$ gem push test_gem_release_gh-0.1.18.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   XXXXX
Successfully registered gem: test_gem_release_gh (0.1.18)

Deleting left over gem file test_gem_release_gh-0.1.18.gem
$ rm -f test_gem_release_gh-0.1.18.gem

Creating GitHub release for test_gem_release_gh version v0.1.18.
GitHub returned 201 (body: "{ ... }")
```

As you can see, I'm seeing the error message, even when a `201` status code is returned, I think the problem is [here](https://github.com/svenfuchs/gem-release/pull/73/files#diff-8fc274c2cf5dd07b89d0066d20ef4639R29), since [`201` is the official ok status code](https://developer.github.com/v3/repos/releases/#create-a-release).

Thanks!

**Comment by PikachuEXE** [comment]
Just fixed expected status code in cd0ee56f326841976cfb043e689ceea259fd4e93

**Comment by PikachuEXE** [comment]
I suppose I will release this next week unless there is something more to test/change
@kennyadsl

**Comment by kennyadsl** [comment]
Fine by me, thanks again, @PikachuEXE!

**Comment by PikachuEXE** [comment]
Releasing this tomorrow

**Comment by PikachuEXE** [comment]
Released as `2.1.0`

**Pull request merged**
